CREATE DATABASE IF NOT EXISTS ecommerce;

CREATE TABLE IF NOT EXISTS categorias (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS produtos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	valor FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS relacionamento (
	id_produto INT REFERENCES produtos(id),
	id_categoria INT REFERENCES categorias(id),
	id_tag INT REFERENCES tags(id)
);
